---
title: "Modeling_copy"
output: html_document
date: "2023-04-20"
---

```{r setup, include=FALSE}
library(readxl)


library(tidyverse)
library(broom)
library(ggplot2)
library(dplyr)
library(plyr)
library(gtrendsR)
library(dplyr)
library(tidyverse)
library(tibble)
library(gridExtra)
library(grid)
library(lubridate)
library(ggplot2)
```

```{r}

UNHCR <- read_excel("UNHCR 2022 Multi-Sector Needs Assessment Consolidated Dataset.xlsx", 
    sheet = "family-level_data")
UA_codes <- read_excel("converting_UA_codes.xlsx")


# Data Cleaning
UNHCR_clean = UNHCR %>% 
  add_column(location = NA)
UNHCR_clean$location[UNHCR_clean$admin1 == "chisinau"] <- "Chisinau"
UNHCR_clean$location[UNHCR_clean$admin1 == "calarasi"] <- "Chisinau"
UNHCR_clean$location[UNHCR_clean$admin1 == "cimislia"] <- "Chisinau"
UNHCR_clean$location[UNHCR_clean$admin1 == "ialoveni"] <- "Chisinau"
UNHCR_clean$location[UNHCR_clean$admin1 == "straseni"] <- "Chisinau"

UNHCR_clean$location[UNHCR_clean$admin1 == "balti"] <- "Balti"
UNHCR_clean$location[UNHCR_clean$admin1 == "telenesti"] <- "Balti"
UNHCR_clean$location[UNHCR_clean$admin1 == "falesti"] <- "Balti"

UNHCR_clean$location[UNHCR_clean$admin1 == "dubarasi"] <- "Transnistria"

UNHCR_clean$location[UNHCR_clean$admin1 == "annenni_noi"] <- "Bender"
UNHCR_clean$location[UNHCR_clean$admin1 == "stefan_vodatabl"] <- "Bender"

# subset based in columns of interest
UNHCR_clean = subset(UNHCR_clean, select = c('location','admin1', "language_preference", "age_speaker", "arrival", "hh_accomodation", "admin_oblast", "displacement_secondary", "displacement_secondary_loc", "displacement_intentions", "displacement_return", "hh_family_size","gender", "age", "marital_status", "health_needed_healthcare", "wg_self_care", "pregnant_breastfeeding", "edu_enrollment", "household_number", "hoh_host_marital", "hoh_host_occupation_sector", "infant_hh", "hh_items_available", "hoh_education", "language_preference_need", "hoh_education_diploma", "hoh_occupation", "hoh_ocupation_sector", "hoh_ua_occupation_same", "hoh_current_occupation", "hoh_current_ocupation_sector", "csi_sold_assets", "csi_spent_savings", "csi_withdrew_children", "csi_sold_house" ))

table(UNHCR_clean$admin_oblast)

```


```{r}
#Trends Data
trends_data = read.csv("Moldova_Trends_Data.csv")
```


















```{r}
gt_time <- '2018-01-01 2022-12-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', 'MD-SN')
gt_topic_codes <- c('/m/014dsx', '/m/03gkl', '/g/122h6md7', '/m/07s_c','/m/01dnzs', '/m/0174k2', '/m/040b_t' )
gt_topic_names <- c('Travel', 'Holiday', 'Labor', 'Unemployment', 'Loan', 'Washing_machine', 'Fridge')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
Mdata1 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    Mdata1 <- rbind(Mdata1, temp)
    Sys.sleep(gt_waiting_time)
  }
}
```


```{r}
gt_time <- '2018-01-01 2022-12-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', 'MD-SN')
gt_topic_codes <- c('/m/07gyp7', '/m/0k8z')
gt_topic_names <- c(  'McDonalds', 'Apple')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
Mdata2 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    Mdata2 <- rbind(Mdata2, temp)
    Sys.sleep(gt_waiting_time)
  }
}

```


```{r}
gt_time <- '2018-01-01 2022-12-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', "MD-SN")
gt_topic_codes <- c( '/m/0h6dlrc', '/m/0h5wpdf', '/m/032tl')
gt_topic_names <- c( 'BMW', 'Mercedes', 'Fashion' )
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
Mdata3 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    Mdata3 <- rbind(Mdata3, temp)
    Sys.sleep(gt_waiting_time)
  }
}

```


```{r}
gt_time <- '2018-01-01 2022-12-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', "MD-SN")
gt_topic_codes <- c( '/m/015gxd', '/g/121mknrx', '/m/07bsy')
gt_topic_names <- c('Emigration',  'Construction', 'Transport')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data4 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data4 <- rbind(data4, temp)
    Sys.sleep(gt_waiting_time)
  }
}



#   ,  '/m/01y857'
#  ,, , 'Rent'


#, ,, ,, '/m/02640pc',  , '/m/05sq5', '/g/11clfj__ql'
#, ,  , , , 'Import',, , 'Patent', 'work.ua'
```

```{r}
gt_time <- '2018-01-01 2022-12-31'
gt_regions <- c('MD-DU', "MD-CT")
gt_topic_codes <- c( '/g/121mknrx', '/m/07bsy')
gt_topic_names <- c('Construction', 'Transport' )
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more <- rbind(data_more, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, 
#, 

 #, , '/m/032tl', '/m/0273t5w', '/m/03w7y7','/m/07gyp7', '/m/0k8z', '/m/027x7n', '/m/014dsx', '/m/03gkl', '/g/122h6md7', '/m/07s_c','/m/01dnzs', '/m/0174k2', '/m/040b_t', '/m/015gxd'

#,  , 'Fashion', 'Mortgage_loan', 'Baggage','McDonalds', 'apple','Fitness', 'Travel', 'Holiday', 'Labor', 'Unemployment', 'Loan', 'Washing_machine', 'Fridge', 'Emigration'
```

```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD')
gt_topic_codes <- c(  '/m/03w7y7','/m/07gyp7', '/m/0k8z', "/m/059z22")
gt_topic_names <- c( 'Baggage','McDonalds', 'apple','Fitness' )
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more1 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more1 <- rbind(data_more1, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, ,, '/m/014dsx', '/m/03gkl', '/g/122h6md7', '/m/07s_c','/m/01dnzs',  '/m/0174k2', '/m/040b_t', '/m/04n7dpf', '/m/0h6dlrc', '/m/0h5wpdf', '/m/032tl', '/m/015gxd', '/g/121mknrx'
#, 'Travel', 'Holiday', 'Labor', 'Unemployment', 'Loan', 'Washing_machine', 'Fridge', 'Interest_rate', 'BMW', 'Mercedes', 'Fashion', 'Emigration',  'Construction'

 #, , , , , , , ,, ', , '/m/015gxd'

#,  , ,, , , , , , , , 'Emigration'
```

```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD')
gt_topic_codes <- c(  '/m/014dsx', '/m/03gkl', '/g/122h6md7','/m/01dnzs',  '/m/0174k2', '/m/040b_t', '/m/04n7dpf', '/m/0h6dlrc', '/m/0h5wpdf', '/m/032tl', '/m/015gxd', '/g/121mknrx')
gt_topic_names <- c( 'Travel', 'Holiday', 'Labor', 'Loan', 'Washing_machine', 'Fridge', 'Interest_rate', 'BMW', 'Mercedes', 'Fashion', 'Emigration',  'Construction' )
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more2 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more2 <- rbind(data_more2, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, ,, 
#, 

 #, , , , , , , ,, ', , '/m/015gxd'

#,  , ,, , , , , , , , 'Emigration'
```



```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD')
gt_topic_codes <- c("/m/07s_c", "/m/0273t5w")
gt_topic_names <- c( 'Unemployment' , 'Mortgage_Loan')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more3 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more3 <- rbind(data_more3, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, ,, 
#, 

 #, , , , , , , ,, ', , '/m/015gxd'

#,  , ,, , , , , , , , 'Emigration'
```



```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD')
gt_topic_codes <- c("/m/07s_c", "/m/0273t5w")
gt_topic_names <- c( 'Unemployment' , 'Mortgage_Loan')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more3 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more3 <- rbind(data_more3, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, ,, 
#, 

 #, , , , , , , ,, ', , '/m/015gxd'

#,  , ,, , , , , , , , 'Emigration'
```




```{r}
# Make giant data set
Moldova_Trends_Data = rbind(data1, data2, data3, data4, data_more1, data_more2,data_more3 )
Moldova_Trends_Data = distinct(Moldova_Trends_Data)

# change the <1 to 0s
 Moldova_Trends_Data <- data.frame(lapply(Moldova_Trends_Data, function(x) {
                  gsub("<1", "0.5", x)
              }))
```

```{r}
write.csv(Moldova_Trends_Data, file = "/Users/jessiebierschenk/Cossack Collectors/Moldova_Trends_Data.csv", row.names=FALSE)

#view(Moldova_Trends_Data)
Moldova_Trends_Data= Moldova_Trends_Data %>% 
  mutate(name = ifelse(geo == 'MD-BA', "Balti", ifelse( geo == 'MD-BD', "Bender", ifelse(geo== "MD-CU", "Chisinau", ifelse(geo == "MD", "Moldova", "Transnistria")))))

Moldova_Trends_Data$date = as.Date(Moldova_Trends_Data$date)
Moldova_Trends_Data$hits = as.numeric(Moldova_Trends_Data$hits)

Moldova_Trends_Data$year = substr(Moldova_Trends_Data$date, 1, 4)

```




```{r}
# Data Cleaning


```

