---
title: "Moldova Exploration"
output:
  pdf_document: default
  html_document: default
date: "2023-03-29"
---
```{r}
library(gtrendsR)
library(dplyr)
library(tidyverse)
library(tibble)
library(gridExtra)
library(grid)
library(lubridate)
```

https://en.wikipedia.org/wiki/ISO_3166-2:MD

https://data.worldbank.org/country/MD

Due to limited international recognition, Transnistria is considered part of Moldova and does not have its own ISO 3166-1 code.


```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', "MD-SN")
gt_topic_codes <- c('/m/014dsx', '/m/03gkl', '/g/122h6md7', '/m/07s_c','/m/01dnzs', '/m/0174k2', '/m/040b_t' )
gt_topic_names <- c('Travel', 'Holiday', 'Labor', 'Unemployment', 'Loan', 'Washing_machine', 'Fridge')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data1 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data1 <- rbind(data1, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#'Bankruptcy', 'Export', 'Interest_rate',
#'/m/01hhz', '/m/01sr3q' , '/m/04n7dpf',

#, 'MD-AN', 'MD-BS', "MD-BR", "MD-CA", "MD-CT", "MD-CL", "MD-CS", "MD-CM", "MD-CR", "MD-DO", "MD-DR", "MD-DU", "MD-ED", "MD-FA", "MD-FL", "MD-GL", "MD-HI", "MD-IA", "MD-LE","MD-NI", "MD-OC", "MD-OR", "MD-RE", "MD-RI", "MD-SI", "MD-SO", "MD-ST", "MD-SD", "MD-SV", "MD-TA", "MD-TE", "MD-UN"

#  '/m/09jx2', '/m/0273t5w', '/m/03w7y7', '/m/0h6dlrc', '/m/0h5wpdf', '/m/07gyp7', '/m/02r33n4', '/m/03gc5x', '/m/015gxd',  '/m/06q07'
#   'Inflation', 'Mortgage_loan', 'Baggage', 'BMW', 'Mercedes', 'McDonalds', 'Calvin_Klein', 'Gucci', 'Emigration', 'Sony'

#, '/m/0k8z', '/m/027x7n', '/m/03nw7w', '/m/0hbm6', '/m/022x_', '/m/0218w7', '/m/032tl', '/m/07s6fsf', '/m/039dhw', '/g/11c1xm7ml2', '/m/06k1r', '/m/01y857', '/m/02640pc', '/g/121mknrx', '/m/07bsy', '/m/05sq5', '/g/11clfj__ql'


#, 'apple','Fitness', 'Recruitment', 'Savings', 'Computer_security', 'Unemployment_benefits', 'Fashion', 'MBA_degree', 'Procurement', 'Prozorro', 'Real_Estate', 'Rent', 'Import', 'Construction', 'Transport', 'Patent', 'work.ua'
```


```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', "MD-SN")
gt_topic_codes <- c( '/m/0273t5w', '/m/03w7y7','/m/07gyp7', '/m/0k8z', '/m/027x7n')
gt_topic_names <- c(  'Mortgage_loan', 'Baggage','McDonalds', 'apple','Fitness')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data2 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data2 <- rbind(data2, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, 'Export', 'Interest_rate',
#, '/m/01sr3q' , '/m/04n7dpf',

#"MD-SN"

#   '/m/0h6dlrc', '/m/0h5wpdf',  '/m/02r33n4', '/m/03gc5x', '/m/015gxd',  '/m/06q07'
#  , 'BMW', 'Mercedes', , 'Calvin_Klein', 'Gucci', 'Emigration', 'Sony'


#, , '/m/03nw7w', '/m/0hbm6', '/m/022x_', '/m/0218w7', '/m/032tl', '/m/07s6fsf', '/m/039dhw', '/g/11c1xm7ml2', '/m/06k1r', '/m/01y857', '/m/02640pc', '/g/121mknrx', '/m/07bsy', '/m/05sq5', '/g/11clfj__ql'
#, , 'Recruitment', 'Savings', 'Computer_security', 'Unemployment_benefits', 'Fashion', 'MBA_degree', 'Procurement', 'Prozorro', 'Real_Estate', 'Rent', 'Import', 'Construction', 'Transport', 'Patent', 'work.ua'

# 


```


```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', "MD-SN")
gt_topic_codes <- c('/m/04n7dpf', '/m/0h6dlrc', '/m/0h5wpdf', '/m/032tl')
gt_topic_names <- c('Interest_rate', 'BMW', 'Mercedes', 'Fashion' )
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data3 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data3 <- rbind(data3, temp)
    Sys.sleep(gt_waiting_time)
  }
}



#   ,  '/m/02r33n4', '/m/03gc5x', '/m/015gxd',  '/m/06q07'
#  ,, , 'Calvin_Klein', 'Gucci', 'Emigration', 'Sony'

# '/m/022x_', 
#, , 'Computer_security', 


#, ,, '/m/07s6fsf', '/m/039dhw', '/g/11c1xm7ml2', '/m/06k1r', '/m/01y857', '/m/02640pc', '/g/121mknrx', '/m/07bsy', '/m/05sq5', '/g/11clfj__ql'

#, ,  , 'MBA_degree', 'Procurement', 'Prozorro', 'Real_Estate', 'Rent', 'Import', 'Construction', 'Transport', 'Patent', 'work.ua'
```


```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD-BA', 'MD-BD', 'MD-CU', "MD-SN")
gt_topic_codes <- c( '/m/015gxd', '/g/121mknrx', '/m/07bsy')
gt_topic_names <- c('Emigration',  'Construction', 'Transport')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data4 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data4 <- rbind(data4, temp)
    Sys.sleep(gt_waiting_time)
  }
}



#   ,  '/m/01y857'
#  ,, , 'Rent'


#, ,, ,, '/m/02640pc',  , '/m/05sq5', '/g/11clfj__ql'
#, ,  , , , 'Import',, , 'Patent', 'work.ua'
```

```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD-DU', "MD-CT")
gt_topic_codes <- c( '/g/121mknrx', '/m/07bsy')
gt_topic_names <- c('Construction', 'Transport' )
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more <- rbind(data_more, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, 
#, 

 #, , '/m/032tl', '/m/0273t5w', '/m/03w7y7','/m/07gyp7', '/m/0k8z', '/m/027x7n', '/m/014dsx', '/m/03gkl', '/g/122h6md7', '/m/07s_c','/m/01dnzs', '/m/0174k2', '/m/040b_t', '/m/015gxd'

#,  , 'Fashion', 'Mortgage_loan', 'Baggage','McDonalds', 'apple','Fitness', 'Travel', 'Holiday', 'Labor', 'Unemployment', 'Loan', 'Washing_machine', 'Fridge', 'Emigration'
```

```{r}
gt_time <- '2010-01-01 2023-01-31'
gt_regions <- c('MD-SV')
gt_topic_codes <- c('/m/032tl' )
gt_topic_names <- c('Fashion')
gt_waiting_time <- 30

# create an empty dataframe to store all datasets
data_more1 <- data.frame(matrix(ncol = 7, nrow = 0))

# use for loop to scrape data 
for (i in 1:length(gt_regions)){
  for (j in 1:length(gt_topic_codes)){
    temp <- gtrends(gt_topic_codes[j], geo = gt_regions[i], time = gt_time)
    temp <- temp[["interest_over_time"]]
    temp["keyword"][temp["keyword"] == gt_topic_codes[j]] =  gt_topic_names[j]
    data_more1 <- rbind(data_more1, temp)
    Sys.sleep(gt_waiting_time)
  }
}

#, ,'/m/0273t5w',
#, , ,'Mortgage_loan',

 #, , , , , , , ,, ', , '/m/015gxd'

#,  , ,, , , , , , , , 'Emigration'
```


```{r}
# Make giant data set
Moldova_Trends_Data = rbind(data1, data2, data3, data4)
Moldova_Trends_Data = distinct(Moldova_Trends_Data)

# change the <1 to 0s
 Moldova_Trends_Data <- data.frame(lapply(Moldova_Trends_Data, function(x) {
                  gsub("<1", "0.5", x)
              }))
```

```{r}
write.csv(Moldova_Trends_Data, file = "/Users/jessiebierschenk/Cossack Collectors/Moldova_Trends_Data.csv", row.names=FALSE)

#view(Moldova_Trends_Data)
Moldova_Trends_Data= Moldova_Trends_Data %>% 
  mutate(name = ifelse(geo == 'MD-BA', "Balti", ifelse( geo == 'MD-BD', "Bender", ifelse(geo== "MD-CU", "Chisinau", "Transnistria"))))

Moldova_Trends_Data$date = as.Date(Moldova_Trends_Data$date)
Moldova_Trends_Data$hits = as.numeric(Moldova_Trends_Data$hits)

Moldova_Trends_Data$year = substr(Moldova_Trends_Data$date, 1, 4)

```


```{r}
Most_Hits =Moldova_Trends_Data %>% 
  group_by(name) %>%
  top_n(1, hits)

tibble(Most_Hits)
```
The max hits were the following topics:

* For Balti: Labor (2011)

* For Bender: Washing Machine (2010), McDonalds (2013)

* For Chisinau: Travel (2021)

* For Transnistria: Apple (2010)


# Travel Hits

```{r}
Travel_hits = ggplot(subset(Moldova_Trends_Data, keyword =='Travel'), aes(x = date, y= hits))+ geom_line(aes(color=name))+labs(title= "Travel Hits Overtime by Region", y="# Hits", x= "Date") +guides(color = guide_legend(title = "Region"))

Travel_hits
```

# Unemployment Hits

```{r}
Unemployment_hits = ggplot(subset(Moldova_Trends_Data, keyword =='Unemployment'), aes(x = date, y= hits))+ geom_line(aes(color=name))+labs(title= "Unemployment Hits Overtime by Region", y="# Hits", x= "Date") +guides(color = guide_legend(title = "Region"))

Unemployment_hits
```


# McDonalds Hits

```{r}
McDonalds_hits = ggplot(subset(Moldova_Trends_Data, keyword =='McDonalds'), aes(x = date, y= hits))+ geom_line(aes(color=name))+labs(title= "McDonalds Hits Overtime by Region", y="# Hits", x= "Date") +guides(color = guide_legend(title = "Region"))

McDonalds_hits
```

# Apple Hits

```{r}
Apple_hits = ggplot(subset(Moldova_Trends_Data, keyword =='apple'), aes(x = date, y= hits))+ geom_line(aes(color=name))+labs(title= "Apple Hits Overtime by Region", y="# Hits", x= "Date") +guides(color = guide_legend(title = "Region"))

Apple_hits

```

# Fitness Hits

```{r}
Fitness_hits = ggplot(subset(Moldova_Trends_Data, keyword =='Fitness'), aes(x = date, y= hits))+ geom_line(aes(color=name))+labs(title= "Fitness Hits Overtime by Region", y="# Hits", x= "Date") +guides(color = guide_legend(title = "Region"))
Fitness_hits

```

# Mortgage Loan Hits

```{r}
Mortgage_loan_hits = ggplot(subset(Moldova_Trends_Data, keyword =='Mortgage_loan'), aes(x = date, y= hits))+ geom_line(aes(color=name))+labs(title= "Mortgage Loan  Hits Overtime by Region", y="# Hits", x= "Date") +guides(color = guide_legend(title = "Region"))
Mortgage_loan_hits

```


```{r}
MD_data = read.csv( "Moldova Country Data.csv")
MD_data = subset(MD_data, select = -c(Country.Name,Country.Code, Indicator.Code) )
MD_data = MD_data%>%
  pivot_longer(cols=c('X2010', 'X2011', 'X2012', 'X2013', 'X2014', 'X2015', 'X2016', 'X2017', 'X2018', 'X2019', 'X2020', 'X2021'), names_to='year', values_to = 'Value')

MD_data$year<-gsub("X","",as.character(MD_data$year))
MD_data$year = as.numeric(MD_data$year)
```

```{r}
ggplot(data = subset(MD_data, Indicator.Name == "Food exports (% of merchandise exports)")) + geom_line(aes(x = year, y = Value)) + labs(title = "Food exports (% of merchandise exports) vs. Year", x = "Year", y = "Food Exports")

```
```{r}
ggplot(data = subset(MD_data, Indicator.Name == "Fuel imports (% of merchandise imports)")) + geom_line(aes(x = year, y = Value)) + labs(title = "Fuel imports (% of merchandise imports) vs. Year", x = "Year", y = "Fuel imports")
```
```{r}
ggplot(data = subset(MD_data, Indicator.Name == "International tourism, expenditures for travel items (current US$)")) + geom_line(aes(x = year, y = Value)) + labs(title = "International tourism, expenditures for travel items (current US$) vs. Year", x = "Year", y = "International tourism")
```
```{r}
ggplot(data = subset(MD_data, Indicator.Name == "Rural population (% of total population)")) + geom_line(aes(x = year, y = Value)) + labs(title = "Rural population (% of total population) vs. Year", x = "Year", y = "Rural Population %")
```
```{r}
ggplot(data = subset(MD_data, Indicator.Name == "Population, female")) + geom_line(aes(x = year, y = Value)) + labs(title = "Population, female vs. Year", x = "Year", y = "Female Population")
```
```{r}
ggplot(data = subset(MD_data, Indicator.Name == "Population growth (annual %)")) + geom_line(aes(x = year, y = Value)) + labs(title = "Population growth (annual %)", x = "Year", y = "Population growth (annual %) Vs. Year") + geom_hline(yintercept = 0, linetype="dashed", color = "red")
```
```{r}
MD_education = MD_data %>% 
  filter(Indicator.Name == "Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)" | Indicator.Name == "Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)")

MD_education = MD_education %>% 
  mutate(ifelse(Indicator.Name == "Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)", "Male", "Female"))

MD_education = MD_education %>%
  rename(Sort = 4)

ggplot(data = MD_education) + geom_point(aes(x = year, y = Value, color = Sort)) + labs(title = "Educational attainment, at least completed short-cycle tertiary, 
      population 25+ vs. Year", x = "Year", y = "Educational attainment, at least completed short-cycle tertiary, population 25+") 
```



