---
title: "Econ 390 Moldova maps"
author: "Michelle Schultze"
date: "2023-03-23"
output:
  word_document: default
  html_document:
    df_print: paged
---


Load packages & import data 

```{r load-import, message=FALSE, warning=FALSE}
library(readxl)
UNHCR <- read_excel("UNHCR 2022 Multi-Sector Needs Assessment Consolidated Dataset.xlsx", 
    sheet = "family-level_data")
UA_codes <- read_excel("converting_UA_codes.xlsx")

library(tidyverse)
library(broom)
library(tidymodels)
library(ggplot2)
library(ggthemes)
library(pls)
library(haven)
library(maps)
library(rgdal)
library(maptools)
library(sf)
library(terra)
library(geodata)
library(rgeos)
library(dplyr)
library(plyr)
library(ggridges)
library(tmap)
library(raster)
```

```{r merge}
test <- UA_codes %>%
  mutate(admin_oblast = No_Dash)

UNHCR <- test %>%
  merge(UNHCR)
```

```{r EDA}
UNHCR %>%
  ggplot(mapping = aes(today)) +
  geom_bar() +
  labs(title = "Timespan", subtitle = "UNHCR Multi-Sector Needs Assessment")

UNHCR %>%
  ggplot(mapping = aes(today)) +
  geom_bar() +
  labs(title = "Timespan by Region", subtitle = "UNHCR Multi-Sector Needs Assessment") + 
  facet_wrap(admin1 ~ .)

UNHCR %>%
  ggplot(mapping = aes(hh_accomodation)) +
  geom_bar() +
  labs(title = "Accomodations of Surveyed Refugees", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  ggplot(mapping = aes(NAME_1)) +
  geom_bar() +
  labs(title = "Origin Oblasts of Surveyed Refugees", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  ggplot(mapping = aes(displacement_return)) +
  geom_bar() +
  labs(title = "Return Conditions of Surveyed Refugees", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


UNHCR %>%
  ggplot(mapping = aes(displacement_intentions)) +
  geom_bar() +
  labs(title = "Intentions of Surveyed Refugees", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


UNHCR %>%
  ggplot(mapping = aes(as.character(hh_family_size))) +
  geom_bar() +
  labs(title = "Household Size of Surveyed Refugees", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  ggplot(mapping = aes(as.Date(arrival))) +
  geom_bar() +
  labs(title = "Arrival Date of Surveyed Refugees", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  arrange(as.numeric(income_humanitarian_assistance), decreasing = FALSE) %>%
  ggplot(mapping = aes(income_humanitarian_assistance)) +
  geom_bar() +
  labs(title = "Income by Means of Humanitarian Assistance", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))




UNHCR %>%
  ggplot(mapping = aes(hh_psychosocial_support)) +
  geom_bar() +
  labs(title = "Psychosocial Support Frequency", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  ggplot(mapping = aes(hh_discrimination_md)) +
  geom_bar() +
  labs(title = "Discrimination Reported", subtitle = "UNHCR Multi-Sector Needs Assessment (May 16-May 31 2022)") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


UNHCR %>%
  filter(displacement_second_country != "N/A") %>%
  ggplot(mapping = aes(displacement_second_country)) +
  geom_bar() +
  labs(title = "Second Country Intentions", subtitle = "If intending to move to a second country other than Moldova") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


```

```{r clean-data}
UNHCR <- UNHCR %>%
  mutate(
    rac_dummy = if_else(rac_non_rac == "rac" | hh_accomodation == "acc_informal_rac", 1, 0),
    relatives_dummy = case_when(hh_accomodation == "acc_relatives" ~ 1,
                             hh_accomodation != "acc_relatives" ~ 0),
    private_dummy = case_when(hh_accomodation == "acc_private" ~ 1,
                             hh_accomodation != "acc_private" ~ 0),
    hotel_dummy = case_when(hh_accomodation == "acc_hotel" ~ 1,
                             hh_accomodation != "acc_hotel" ~ 0),
    moldovan_dummy = case_when(hh_accomodation == "acc_moldovan" ~ 1,
                             hh_accomodation != "acc_moldovan" ~ 0)) %>%
  mutate(age_speaker = as.numeric(age_speaker),
         income_formal_work = as.numeric(income_formal_work),
         income_daily_labor = as.numeric(income_daily_labor),
         income_business = as.numeric(income_business),
         income_savings = as.numeric(income_savings),
         income_government = as.numeric(income_government),
         income_remittances = as.numeric(income_remittances),
         income_support_family = as.numeric(income_support_family),
         income_humanitarian_assistance = as.numeric(income_humanitarian_assistance),
         income_donations = as.numeric(income_donations),
         income_other = as.numeric(income_other),
         hh_total_count = as.numeric(hh_total_count),
         children_count = as.numeric(children_count),
         expenses_family = as.numeric(expenses_family),
         expenses_food = as.numeric(expenses_food),
         expenses_rent = as.numeric(expenses_rent),
         expenses_water = as.numeric(expenses_water),
         expenses_nonfood = as.numeric(expenses_nonfood),
         expenses_utilities = as.numeric(expenses_utilities),
         expenses_fuel = as.numeric(expenses_fuel),
         expenses_transport = as.numeric(expenses_transport),
         expenses_communication = as.numeric(expenses_communication),
         expenses_other = as.numeric(expenses_other))

UNHCR["income_formal_work"][UNHCR["income_formal_work"] == "N/A"] <- 0
UNHCR["income_daily_labor"][UNHCR["income_daily_labor"] == "N/A"] <- 0
UNHCR["income_business"][UNHCR["income_business"] == "N/A"] <- 0
UNHCR["income_savings"][UNHCR["income_savings"] == "N/A"] <- 0
UNHCR["income_government"][UNHCR["income_government"] == "N/A"] <- 0
UNHCR["income_remittances"][UNHCR["income_remittances"] == "N/A"] <- 0
UNHCR["income_support_family"][UNHCR["income_support_family"] == "N/A"] <- 0
UNHCR["income_humanitarian_assistance"][UNHCR["income_humanitarian_assistance"] == "N/A"] <- 0
UNHCR["income_donations"][UNHCR["income_donations"] == "N/A"] <- 0
UNHCR["income_other"][UNHCR["income_other"] == "N/A"] <- 0
UNHCR["expenses_family"][UNHCR["expenses_family"] == "N/A"] <- 0
UNHCR["expenses_food"][UNHCR["expenses_food"] == "N/A"] <- 0
UNHCR["expenses_rent"][UNHCR["expenses_rent"] == "N/A"] <- 0
UNHCR["expenses_water"][UNHCR["expenses_water"] == "N/A"] <- 0
UNHCR["expenses_nonfood"][UNHCR["expenses_nonfood"] == "N/A"] <- 0
UNHCR["expenses_utilities"][UNHCR["expenses_utilities"] == "N/A"] <- 0
UNHCR["expenses_fuel"][UNHCR["expenses_fuel"] == "N/A"] <- 0
UNHCR["expenses_transport"][UNHCR["expenses_transport"] == "N/A"] <- 0
UNHCR["expenses_communication"][UNHCR["expenses_communication"] == "N/A"] <- 0
UNHCR["expenses_other"][UNHCR["expenses_other"] == "N/A"] <- 0
```

```{r sum-stats}




UNHCR %>%
  group_by(hh_accomodation) %>%
  dplyr::summarize(n = n(),
                   freq = n()/704) %>%
  filter(n > 10)




UNHCR %>%
  filter(hoh_probing_qs == "yes") %>%
  group_by(displacement_intentions) %>%
  dplyr::summarize(
    russian_pref_freq = mean(language_preference_russian, na.rm=T),
    avg_arrival = mean(ymd(arrival), na.rm=T),
    avg_age = mean(age_speaker, na.rm=T),
    rac_freq = mean(rac_dummy, na.rm=T),
    private_freq = mean(private_dummy, na.rm=T),
    hotel_freq = mean(hotel_dummy, na.rm=T),
    relatives_freq = mean(relatives_dummy, na.rm=T),
    moldovan_freq = mean(moldovan_dummy, na.rm=T),
    avg_hh_total = mean(hh_total_count, na.rm=T),
    avg_children = mean(children_count, na.rm=T),
    avg_income_formal_work = mean(income_formal_work, na.rm=T),
    avg_income_daily_labor = mean(income_daily_labor, na.rm=T),
    avg_income_business = mean(income_business, na.rm=T),
    avg_income_savings = mean(income_savings, na.rm=T),
    avg_income_government = mean(income_government, na.rm=T),
    avg_income_remittances = mean(income_remittances, na.rm=T),
    avg_income_support_family = mean(income_support_family, na.rm=T),
    avg_income_humanitarian_assistance = mean(income_humanitarian_assistance, na.rm=T),
    avg_income_donations = mean(income_donations, na.rm=T),
    avg_income_other = mean(income_other, na.rm=T),
    avg_expenses_food = mean(expenses_food, na.rm=T),
    avg_expenses_family = mean(expenses_family, na.rm=T),
    avg_expenses_rent = mean(expenses_rent, na.rm=T),
    avg_expenses_water = mean(expenses_water, na.rm=T),
    avg_expenses_utilities = mean(expenses_utilities, na.rm=T),
    avg_expenses_nonfood = mean(expenses_nonfood, na.rm=T),
    avg_expenses_fuel = mean(expenses_fuel, na.rm=T),
    avg_expenses_transport = mean(expenses_transport, na.rm=T),
    avg_expenses_communication = mean(expenses_communication, na.rm=T),
    avg_expenses_other = mean(expenses_other, na.rm=T),
    n = n()
    ) %>%
  filter(n >10)

# On average, heads of household who intend to eventually move to a secondary country after Moldova are younger, slightly less likely to prefer the Russian language, and arrived in Moldova later. They are also more likely to have a larger family with more children, draw more of their income from their savings, and receive less humanitarian assistance.
# Also, 44% of households who intend to move to a secondary country live in RACs (Refugee Accommodation Centers), compared to 19-27% of those who intend to return, stay, or don't know.

# Households who are uncertain about their intentions for leaving or staying in Moldova are most likely to live in hotels (32%) or RACs (27%).

UNHCR %>%
  group_by(displacement_intentions) %>%
  dplyr::summarize(n = n(),
                   freq = n()/704) %>%
  filter(n > 10)

# Most surveyed wanted to stay in Moldova.






UNHCR %>%
  filter(hoh_probing_qs == "yes") %>%
  group_by(hh_accomodation) %>%
  dplyr::summarize(
    russian_pref_freq = mean(language_preference_russian, na.rm=T),
    avg_arrival = mean(ymd(arrival), na.rm=T),
    avg_age = mean(age_speaker, na.rm=T),
    avg_hh_total = mean(hh_total_count, na.rm=T),
    avg_children = mean(children_count, na.rm=T),
    avg_income_formal_work = mean(income_formal_work, na.rm=T),
    avg_income_daily_labor = mean(income_daily_labor, na.rm=T),
    avg_income_business = mean(income_business, na.rm=T),
    avg_income_savings = mean(income_savings, na.rm=T),
    avg_income_government = mean(income_government, na.rm=T),
    avg_income_remittances = mean(income_remittances, na.rm=T),
    avg_income_support_family = mean(income_support_family, na.rm=T),
    avg_income_humanitarian_assistance = mean(income_humanitarian_assistance, na.rm=T),
    avg_income_donations = mean(income_donations, na.rm=T),
    avg_income_other = mean(income_other, na.rm=T),
    avg_expenses_food = mean(expenses_food, na.rm=T),
    avg_expenses_family = mean(expenses_family, na.rm=T),
    avg_expenses_rent = mean(expenses_rent, na.rm=T),
    avg_expenses_water = mean(expenses_water, na.rm=T),
    avg_expenses_utilities = mean(expenses_utilities, na.rm=T),
    avg_expenses_nonfood = mean(expenses_nonfood, na.rm=T),
    avg_expenses_fuel = mean(expenses_fuel, na.rm=T),
    avg_expenses_transport = mean(expenses_transport, na.rm=T),
    avg_expenses_communication = mean(expenses_communication, na.rm=T),
    avg_expenses_other = mean(expenses_other, na.rm=T),
    n = n()
    ) %>%
  filter(n >10)

# On average, those living with Moldovans or relatives have less children and smaller family sizes.
# On average, those living in hotels tend to draw the most from their savings (and then humanitarian assistance) as opposed to other forms of income, such as formal work. They also pay the most for rent by far (3000 per month on average).
# Ukrainians living in formal or informal RACs in Moldova tend to have the lowest food and utilities expenditures on average, relative to those living in other accommodations.
# Those living with relatives or in RACs pay the lowest amount of rent relative to those living in other accommodations. 
# Those living with relatives or Moldovans pay the most for transport per month.



test <- UNHCR %>%
  filter(hoh_probing_qs == "yes") %>%
  group_by(NAME_1) %>%
  dplyr::summarize(
    russian_pref_freq = mean(language_preference_russian, na.rm=T),
    avg_arrival = mean(ymd(arrival), na.rm=T),
    avg_age = mean(age_speaker, na.rm=T),
    rac_freq = mean(rac_dummy, na.rm=T),
    private_freq = mean(private_dummy, na.rm=T),
    hotel_freq = mean(hotel_dummy, na.rm=T),
    relatives_freq = mean(relatives_dummy, na.rm=T),
    moldovan_freq = mean(moldovan_dummy, na.rm=T),
    avg_hh_total = mean(hh_total_count, na.rm=T),
    avg_children = mean(children_count, na.rm=T),
    avg_income_formal_work = mean(income_formal_work, na.rm=T),
    avg_income_daily_labor = mean(income_daily_labor, na.rm=T),
    avg_income_business = mean(income_business, na.rm=T),
    avg_income_savings = mean(income_savings, na.rm=T),
    avg_income_government = mean(income_government, na.rm=T),
    avg_income_remittances = mean(income_remittances, na.rm=T),
    avg_income_support_family = mean(income_support_family, na.rm=T),
    avg_income_humanitarian_assistance = mean(income_humanitarian_assistance, na.rm=T),
    avg_income_donations = mean(income_donations, na.rm=T),
    avg_income_other = mean(income_other, na.rm=T),
    avg_expenses_food = mean(expenses_food, na.rm=T),
    avg_expenses_family = mean(expenses_family, na.rm=T),
    avg_expenses_rent = mean(expenses_rent, na.rm=T),
    avg_expenses_water = mean(expenses_water, na.rm=T),
    avg_expenses_utilities = mean(expenses_utilities, na.rm=T),
    avg_expenses_nonfood = mean(expenses_nonfood, na.rm=T),
    avg_expenses_fuel = mean(expenses_fuel, na.rm=T),
    avg_expenses_transport = mean(expenses_transport, na.rm=T),
    avg_expenses_communication = mean(expenses_communication, na.rm=T),
    avg_expenses_other = mean(expenses_other, na.rm=T),
    n = n()
    ) %>%
  filter(n >10)

# Those coming from Donetsk and Kherson arrived in Moldova the latest on average.

data_oblasts <- test %>%
  dplyr::select(NAME_1)

UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  ggplot(aes(NAME_1, fill=hh_accomodation)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  ggplot(aes(NAME_1, hh_family_size)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  ggplot(aes(hh_accomodation, expenses_food)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  ggplot(aes(hh_accomodation, expenses_rent)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  ggplot(aes(NAME_1, fill=displacement_intentions)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  mutate(goback = case_when(displacement_intentions == "Idntknow" | displacement_intentions == "no_response"~ "Unknown",
                            displacement_intentions == "move_md" | displacement_intentions == "move_outmd" | displacement_intentions == "stay_location" | displacement_intentions == "stay_different" ~ "Not return to UA", 
                            displacement_intentions == "return_ua_origin" | displacement_intentions == "return_ua_other"~ "Return to UA")) %>%
  ggplot(aes(NAME_1, fill=goback)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  ggplot(aes(NAME_1, fill=displacement_return)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  ggplot(aes(as.numeric(expenses_food), as.numeric(children_count))) +
  geom_point() +
  geom_smooth(method="lm")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  mutate(goback = case_when(displacement_intentions == "Idntknow" | displacement_intentions == "no_response"~ "Unknown",
                            displacement_intentions == "move_md" | displacement_intentions == "move_outmd" | displacement_intentions == "stay_location" | displacement_intentions == "stay_different" ~ "Not return to UA", 
                            displacement_intentions == "return_ua_origin" | displacement_intentions == "return_ua_other"~ "Return to UA")) %>%
  ggplot(aes(as.character(hh_total_count), fill=goback)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))







UNHCR %>%
  filter(hoh_probing_qs == "yes") %>%
  group_by(as.character(children_count)) %>%
  dplyr::summarize(
    russian_pref_freq = mean(language_preference_russian, na.rm=T),
    avg_arrival = mean(ymd(arrival), na.rm=T),
    avg_age = mean(age_speaker, na.rm=T),
    rac_freq = mean(rac_dummy, na.rm=T),
    private_freq = mean(private_dummy, na.rm=T),
    hotel_freq = mean(hotel_dummy, na.rm=T),
    relatives_freq = mean(relatives_dummy, na.rm=T),
    moldovan_freq = mean(moldovan_dummy, na.rm=T),
    avg_children = mean(children_count, na.rm=T),
    avg_income_formal_work = mean(income_formal_work, na.rm=T),
    avg_income_daily_labor = mean(income_daily_labor, na.rm=T),
    avg_income_business = mean(income_business, na.rm=T),
    avg_income_savings = mean(income_savings, na.rm=T),
    avg_income_government = mean(income_government, na.rm=T),
    avg_income_remittances = mean(income_remittances, na.rm=T),
    avg_income_support_family = mean(income_support_family, na.rm=T),
    avg_income_humanitarian_assistance = mean(income_humanitarian_assistance, na.rm=T),
    avg_income_donations = mean(income_donations, na.rm=T),
    avg_income_other = mean(income_other, na.rm=T),
    avg_expenses_food = mean(expenses_food, na.rm=T),
    avg_expenses_family = mean(expenses_family, na.rm=T),
    avg_expenses_rent = mean(expenses_rent, na.rm=T),
    avg_expenses_water = mean(expenses_water, na.rm=T),
    avg_expenses_utilities = mean(expenses_utilities, na.rm=T),
    avg_expenses_nonfood = mean(expenses_nonfood, na.rm=T),
    avg_expenses_fuel = mean(expenses_fuel, na.rm=T),
    avg_expenses_transport = mean(expenses_transport, na.rm=T),
    avg_expenses_communication = mean(expenses_communication, na.rm=T),
    avg_expenses_other = mean(expenses_other, na.rm=T),
    n = n()
    ) %>%
  filter(n >10)

# Those with 0 kids are on average older and arrived later.
# Seems to be a trend: living with relatives or Moldovans is more common if a household has less kids. Living in RACs is more common with more kids.


UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  ggplot(aes(children_count, rac_dummy)) +
  geom_point() +
  geom_smooth(method = "lm")



UNHCR %>%
  filter(children_count < 5) %>%
  ggplot() +
  geom_point(aes(children_count, relatives_dummy)) +
  geom_point(aes(children_count, rac_dummy)) +
  geom_point(aes(children_count, moldovan_dummy)) +
  geom_smooth(aes(children_count, relatives_dummy), method = "lm", color = "purple") +
  geom_smooth(aes(children_count, rac_dummy), method = "lm", color = "red") +
  geom_smooth(aes(children_count, moldovan_dummy), method = "lm", color = "blue")


relatives_dummy = "purple"
rac_dummy = "red"
moldovan_dummy = "blue"


UNHCR %>%
  ggplot() +
  geom_point(aes(arrival, children_count), color = "red") +
  geom_smooth(aes(arrival, children_count), method = "lm", color = "red") +
  geom_point(aes(arrival, hh_total_count), color = "blue") +
  geom_smooth(aes(arrival, hh_total_count), method = "lm", color = "blue")

UNHCR %>%
  mutate(infant = if_else(infant_hh == "yes", 1, 0)) %>%
  ggplot(aes(arrival, infant)) +
  geom_point() +
  geom_smooth(method = "lm") 


UNHCR %>%
  ggplot(aes(hoh_occupation, children_count)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(NAME_1 %in% c(data_oblasts$NAME_1)) %>%
  ggplot(aes(NAME_1, fill=hoh_occupation)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(hh_accomodation != "acc_not_specified") %>%
  ggplot(aes(hh_accomodation, fill=hoh_occupation)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(hh_accomodation != "acc_not_specified") %>%
  ggplot(aes(hoh_occupation, fill=hh_accomodation)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  filter(hoh_occupation != "no_answer") %>%
  ggplot(aes(age_speaker, fill=hoh_occupation)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

UNHCR %>%
  ggplot(aes(hoh_occupation, fill=as.character(age_speaker))) +
  geom_bar(position="fill") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  ggplot(aes(hoh_occupation, age_speaker)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  ggplot() +
  geom_density_ridges2(aes(x = age_speaker, y = hoh_occupation)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

  

UNHCR %>%
  ggplot() +
  geom_density_ridges2(aes(x = children_count, y = hoh_occupation)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

  
UNHCR %>%
  ggplot() +
  geom_density_ridges2(aes(x = hh_total_count, y = hoh_occupation)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))



UNHCR %>%
  mutate(goback = case_when(displacement_intentions == "Idntknow" | displacement_intentions == "no_response"~ "Unknown",
                            displacement_intentions == "move_md" | displacement_intentions == "move_outmd" | displacement_intentions == "stay_location" | displacement_intentions == "stay_different" ~ "Not return to UA", 
                            displacement_intentions == "return_ua_origin" | displacement_intentions == "return_ua_other"~ "Return to UA")) %>%
  ggplot(aes(hoh_occupation, fill=goback)) +
  geom_bar(position="fill", color="black") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))




```


```{r}


#download.file("https://geodata.ucdavis.edu/gadm/gadm4.1/shp/gadm41_UKR_shp.zip",destfile="data/ukraine_map.zip")

#system("unzip data/ukraine_map.zip")

map_1 <- readOGR( 
  dsn= paste0(getwd()) , 
  layer="gadm41_UKR_1",
  verbose=FALSE, stringsAsFactors = FALSE)

test2 <- UNHCR %>%
  filter(hoh_probing_qs == "yes") %>%
  group_by(NAME_1) %>%
  dplyr::summarize(
    russian_pref_freq = mean(language_preference_russian, na.rm=T),
    avg_arrival = mean(ymd(arrival), na.rm=T),
    avg_age = mean(age_speaker, na.rm=T),
    rac_freq = mean(rac_dummy, na.rm=T),
    private_freq = mean(private_dummy, na.rm=T),
    hotel_freq = mean(hotel_dummy, na.rm=T),
    relatives_freq = mean(relatives_dummy, na.rm=T),
    moldovan_freq = mean(moldovan_dummy, na.rm=T),
    avg_hh_total = mean(hh_total_count, na.rm=T),
    avg_children = mean(children_count, na.rm=T),
    avg_income_formal_work = mean(income_formal_work, na.rm=T),
    avg_income_daily_labor = mean(income_daily_labor, na.rm=T),
    avg_income_business = mean(income_business, na.rm=T),
    avg_income_savings = mean(income_savings, na.rm=T),
    avg_income_government = mean(income_government, na.rm=T),
    avg_income_remittances = mean(income_remittances, na.rm=T),
    avg_income_support_family = mean(income_support_family, na.rm=T),
    avg_income_humanitarian_assistance = mean(income_humanitarian_assistance, na.rm=T),
    avg_income_donations = mean(income_donations, na.rm=T),
    avg_income_other = mean(income_other, na.rm=T),
    avg_expenses_food = mean(expenses_food, na.rm=T),
    avg_expenses_family = mean(expenses_family, na.rm=T),
    avg_expenses_rent = mean(expenses_rent, na.rm=T),
    avg_expenses_water = mean(expenses_water, na.rm=T),
    avg_expenses_utilities = mean(expenses_utilities, na.rm=T),
    avg_expenses_nonfood = mean(expenses_nonfood, na.rm=T),
    avg_expenses_fuel = mean(expenses_fuel, na.rm=T),
    avg_expenses_transport = mean(expenses_transport, na.rm=T),
    avg_expenses_communication = mean(expenses_communication, na.rm=T),
    avg_expenses_other = mean(expenses_other, na.rm=T),
    n = n()
    ) 
```


```{r doc-maps}
ukraine <- getData("GADM", country="UKR", level=1)

ukraine@data <- ukraine@data %>%
  merge(test2, by = "NAME_1") %>%
  mutate(n == as.numeric(n))

library(RColorBrewer)
my_colors <- brewer.pal(6, "Reds") 
my_colors <- colorRampPalette(my_colors)(6)

class_of_country <- cut(test2$avg_arrival, 6)
my_colors <- my_colors[as.numeric(class_of_country)]

plot(ukraine , col=my_colors, main = "Moldovan migrants total from each oblast")

```

