---
title: "Econ 390 Moldova maps"
author: "Michelle Schultze"
date: "2023-03-23"
output:
  word_document: default
  html_document:
    df_print: paged
---

Load packages & import data

```{r load-import, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(tidymodels)
library(ggplot2)
library(ggthemes)
library(pls)
library(haven)
library(maps)
library(rgdal)
library(maptools)
library(sf)
library(terra)
library(plyr) 
library(geodata)
```

```{r map-0, message=FALSE, warning=FALSE, include=FALSE}
## make a df with only the country to overlap
map_data_es <- map_data('world')[map_data('world')$region == "Moldova",]
## The map (maps + ggplot2 )
ggplot() +
    ## First layer: worldwide map
    geom_polygon(data = map_data("world"),
                 aes(x=long, y=lat, group = group),
                 color = '#9c9c9c', fill = '#f3f3f3') +
    ## Second layer: Country map
    geom_polygon(data = map_data_es,
                 aes(x=long, y=lat, group = group),
                 color = 'red', fill = 'pink') +
    coord_map() +
    coord_fixed(1.3,
                xlim = c(10, 40),
                ylim = c(40, 60)) +
    ggtitle("Moldova") +
    theme(panel.background =element_rect(fill = 'blue'))



```

```{r map-orig}
library(sf)
library(ggplot2)
library(rgdal)
library(rgeos)

#Reading the shapefiles
sf <- st_read(dsn="/Users/michelle/econ390/project-git/map resources/gadm41_MDA_1.shp")
shape <- readOGR(dsn="/Users/michelle/econ390/project-git/map resources/gadm41_MDA_1.shp")

plot(sf["NAME_1"], axes = TRUE, main = "Districts")

ggplot() + 
  geom_sf(data = sf, aes(fill = NAME_1)) + theme(legend.position = "none")

#Mission: color the following locales: c("Bălţi", "Bender", "Chişinău", "Transnistria")

sf <- sf %>%
  mutate(ofinterest = case_when(NAME_1 %in% c("Bălţi", "Bender", "Chişinău") ~ "Cities", 
                                NAME_1 %in% "Transnistria" ~ "Transnistria")) 

ggplot() + 
  geom_sf(data = sf, aes(fill = ofinterest)) + theme_bw()

```



